### ISSUE TITLE
Creare file p7m

### ISSUE THREAD

**Issue by ferroch85** [FatturaElettronica/FatturaElettronica.Extensions#10]
Dato che è stata introdotta la lettura delle fatture firmate, non sarebbe utile creare un metodo che sfrutta sempre Bouncy Castle per apporre una firma dato in input un X509Certificate2 ?

**Comment by nicolaiarocci** [comment]
Sarebbe cosa buona e giusta. Se vuoi contribuire con una pull request, la valuterò con grande interesse.

**Comment by nicolaiarocci** [comment]
Addressed with #14
