### ISSUE TITLE
Errore Firma con CNS

### ISSUE THREAD

**Issue by AlexBream** [FatturaElettronica/FatturaElettronica.Extensions#16]
Ciao,
più che una issue è una info: sto provando a generare il p7m con la firma contenuta nella smart card CNS (Carta Nazionale Servizi)

Il mio codice è questo:

            X509Certificate2 cert = null; // GetDefaultCertificateStoredOnTheCard();

            foreach (var item in my.Certificates)
            {
                var issuer = item.GetNameInfo(X509NameType.DnsName, true);

                if (issuer == "InfoCert Firma Qualificata 2")
                {
                    cert = item;
                }
            }

	    FatturaElettronicaSignedFileExtension.WriteXmlSigned(fattura, cert, file_p7m);

Ottengo l'errore "Impossibile Firmare il contenuto del file", Indagando sul sorgente ho verificato un problema piuttosto diffuso, che ho riscontrato (finora) solo con le CNS, che restituisce errore  -1073741275

vedi: https://stackoverflow.com/questions/52755574/digital-sign-with-sha256-with-c-sharp

**Comment by nicolaiarocci** [comment]
Come per #35 chiudo, ma rimane indicizzato. Grazie Ale.
