### ISSUE TITLE
File in uso

### ISSUE THREAD

**Issue by Fax3D** [FatturaElettronica/FatturaElettronica.Extensions#17]
Dopo aver letto un file .p7m usando il metodo ReadXmlSigned, il file risulta "bloccato" e non è possibile ne' cancellarlo ne' spostarlo in quanto la classe File dice che è in uso da un altro processo.

Questo non accade leggendo un file non firmato tramite il metodo ReadXml.

Grazie

**Comment by nicolaiarocci** [comment]
@ferroch85 ci dai una occhiata tu?

**Comment by emanuele-fasano** [comment]
@nicolaiarocci @ferroch85, credo che il problema sia dovuto alla linea 18 del file FatturaElettronicaSignedFileExtension.cs:
`CmsSignedData signedFile = new CmsSignedData(new FileStream(filePath, FileMode.Open, FileAccess.Read));`
Il filestream aperto qui non viene mai più chiuso.

**Comment by scuderip** [comment]
Anche io ho riscontrato il problema, e la causa è proprio li, io ho risolto dichiarando il fileStream all'interno di una using

**Comment by Fax3D** [comment]
Grazie ragazzi!

**Comment by Fax3D** [comment]
Potreste pubblicare su Nuget l'aggiornamento con il fix di questo bug? Per ora vedo ancora la 1.1.0.
Grazie
