### ISSUE TITLE
Impossibile leggere file firmato in ricezione

### ISSUE THREAD

**Issue by CyberMike97** [FatturaElettronica/FatturaElettronica.Extensions#29]
Ciao, sto utilizzando la libreria per poter leggere dei file ricevuti (sia firmati che non) dallo SDI, ma con un preciso file ricevo la seguente eccezione:

`FatturaElettronica.Extensions.FatturaElettronicaSignatureException: "Una firma non corrisponde al certificato contenuto nel file"`

Secondo me potrebbe essere la firma del file che non è supportata dalla libreria.
Allego due immagini dell'header e del footer p7m di questo file che sembra non essere uguale ad altri file firmati che ho ricevuto.

![img1](https://user-images.githubusercontent.com/33720244/51174329-d6014500-18b7-11e9-9291-7e0df8ed9649.jpg)
![img2](https://user-images.githubusercontent.com/33720244/51174330-d699db80-18b7-11e9-8e7c-551a61230837.jpg)

**Comment by nicolaiarocci** [comment]
Ciao, hai provato a usare opzione per evitare convalida della firma:

     // Legge file con firma digitale evitando di convalidarne la firma
     fattura.ReadXmlSigned("IT02182030391_31.xml.p7m", validateSignature: false);

**Comment by CyberMike97** [comment]
Ciao, ho provato ad usare l'opzione per evitare la convalida ed ha funzionato.
Grazie del supporto.
