### ISSUE TITLE
Possibilita di leggere file p7m online

### ISSUE THREAD

**Issue by karamkorotani** [FatturaElettronica/FatturaElettronica.Extensions#32]
E' possibile leggere file p7m firmato ed estrarre il contenuto, sempre su online, visto che noi utilizziamo di piu php,ajax e java ????

**Comment by nicolaiarocci** [comment]
No.

**Comment by Tudor44** [comment]
> E' possibile leggere file p7m firmato ed estrarre il contenuto, sempre su online, visto che noi utilizziamo di piu php,ajax e java ????

Se ti può interessare io uso questo:
https://postecert.poste.it/verificatore/service?type=0
