### ISSUE TITLE
Namiral root CA

### ISSUE THREAD

**Issue by AlexBream** [FatturaElettronica/FatturaElettronica.Extensions#35]
Ciao a tutti, in alcuni casi i p7m firmati da Namiral non vengono validati per un errore del certificato, questo perché in Windows non viene installato il certificato CA di Namiral scaricabile dal seguente link:
https://docs.namirialtsp.com/documents/NamirialCAFirmaQualificata.crt.

**Comment by nicolaiarocci** [comment]
Ciao Alessandro, grazie per il suggerimento. Chiudo il ticket, ma rimane indicizzato per chi cercasse questa informazione. 

Non sarebbe male aggiungere un FAQ.md al repository dove inserire questo tipo di notizie e informazioni (inclusa la tua precedente #16.)
