### ISSUE TITLE
Rendere PUBLIC ReadXmlSigned che usa lo Stream

### ISSUE THREAD

**Issue by neoDD69** [FatturaElettronica/FatturaElettronica.Extensions#39]
Mi riferisco a questo metodo:
private static void ReadXmlSigned(Fattura fattura, Stream stream, bool validateSignature)

Io in un caso ho già lo stream pronto e per usare queste estensioni dovrei salvare lo stream che ho già in un file temporaneo, passarlo al metodo public che lo trasforma in uno stream e lo elabora e poi cancellare il file temporaneo.

Se potessi accedere al metodo principale che usa lo stream farei prima e meglio.
è possibile?

Grazie.

**Comment by Fax3D** [comment]
Ho la stessa necessità anche io, sarebbe davvero comodo.
