### ISSUE TITLE
IOException

### ISSUE THREAD

**Issue by Fax3D** [FatturaElettronica/FatturaElettronica.Extensions#42]
Buongiorno,

nel tentativo di leggere alcuni xml, ottengo il seguente errore:

IOException reading content. - unknown tag 28 encountered

Se necessario posso fornirvi privatamente alcuni file sui quali ho il problema.

Grazie

**Comment by Fax3D** [comment]
Allego tutto lo stack trace per completezza:

Org.BouncyCastle.Cms.CmsException: IOException reading content. ---> System.IO.IOException: unknown tag 28 encountered
   in Org.BouncyCastle.Asn1.Asn1InputStream.BuildObject(Int32 tag, Int32 tagNo, Int32 length) in D:\a\1\s\crypto\src\asn1\Asn1InputStream.cs:riga 109
   in Org.BouncyCastle.Asn1.Asn1InputStream.ReadObject() in D:\a\1\s\crypto\src\asn1\Asn1InputStream.cs:riga 207
   in Org.BouncyCastle.Cms.CmsUtilities.ReadContentInfo(Asn1InputStream aIn) in D:\a\1\s\crypto\src\cms\CMSUtils.cs:riga 56
   --- Fine della traccia dello stack dell'eccezione interna ---
   in Org.BouncyCastle.Cms.CmsUtilities.ReadContentInfo(Asn1InputStream aIn) in D:\a\1\s\crypto\src\cms\CMSUtils.cs:riga 60
   in Org.BouncyCastle.Cms.CmsUtilities.ReadContentInfo(Stream input) in D:\a\1\s\crypto\src\cms\CMSUtils.cs:riga 48
   in FatturaElettronica.Extensions.FatturaElettronicaSignedFileExtension.ReadXmlSigned(Fattura fattura, String filePath, Boolean validateSignature)
   in EInvoicesAPI.Services.EInvoicesService.GetInvoiceFromFile(String pFilePath, List`1 pAllowedVatCode, Boolean pAttachXML, String& oXmlError) in C:\TFS\B1Boost\Trunk\Server\Modules\EInvoices\EInvoicesAPI\Services\EInvoicesService.cs:riga 2105

**Comment by Fax3D** [comment]
Ho scoperto la causa del problema, potrebbe essere d'aiuto anche ad altri: il mio intermediario (Aruba) a volte invia dei file con estensione .p7m anche se non sono firmati e si tratta di semplici xml, pertanto l'errore che ho segnalato era dovuto al fatto che tentavo di leggere il file con il metodo ReadXmlSigned().

A tal proposito mi viene un suggerimento: non si potrebbe fare in modo che il metodo ReadXml() sia in grado di capire da solo se il file è firmato oppure no, in modo da evitare inconvenienti di questo tipo?

Grazie.

**Comment by nicolaiarocci** [comment]
Potresti wrappare la lettura del p7m in un blocco try..catch e ripiegare (fallback) sul `ReadXml` in caso di eccezione. Se guardi il codice di `ReadXmlSigned` vedrai che già adottiamo questa tecnica per gestire i rari base64-encoded.

Detto questo, non sono un fan della troppa "automagia", soprattutto nelle librerie per developer. In Python diciamo che "explicit is better than implicit". Nel caso specifico, se Aruba genera falsi file .p7m,  ebbene dovrebbero intervenire e risolvere il problema. Aggiungo che sospetto il problema non sia nemmeno dell'intermediario (Aruba), ma di chi ha prodotto l'originale della fattura.

**Comment by Fax3D** [comment]
Grazie per il suggerimento, in effetti avevo già risolto così mettendo un bel try catch.
