### ISSUE TITLE
ReadXmlSigned e ReadXmlSignedBase64

### ISSUE THREAD

**Issue by ardennext99** [FatturaElettronica/FatturaElettronica.Extensions#43]
Ciao, ho un problema tentando di utilizzare il metodo ReadXmlSignedBase64 e ReadXmlSigned.
in pratica mi viene segnalato sempre l'errore: "cannot convert from 'System.Xml.XmlReader' to 'String' ".
se invece utilizzo ReadXml  non da problemi.

![capture](https://user-images.githubusercontent.com/15669149/52714800-1d542180-2f9b-11e9-96dc-a293896f861d.JPG)

Sbaglio io o c'è qualcosa che va sistemato?

**Comment by nicolaiarocci** [comment]
Ciao, a rapida occhiata direi che:

- `ReadXmlSignedBase64` accetta un filepath (stringa) e non uno stream;
- `ReadXmlSigned` che accetta uno stream è disponibile dalla 1.4. Che versione stai usando?
