### ISSUE TITLE
Problemi Installazione FatturaElettronica.Extension

### ISSUE THREAD

**Issue by Lion14** [FatturaElettronica/FatturaElettronica.Extensions#44]
Non riesco in nessun modo o maniera a installare l'estensione. La versione normale senza extension l'ho installata e funziona correttamente.

Gravità	Codice	Descrizione	Progetto	File	Riga	Stato eliminazione
Errore		Non è stato possibile installare il pacchetto 'FatturaElettronica.Extensions 1.4.0'. Si sta tentando di eseguire l'installazione in un progetto destinato a '.NETFramework,Version=v4.5', ma il pacchetto non contiene riferimenti ad assembly o file di dati compatibili con il framework. Per altre informazioni, contattare l'autore del pacchetto.			0

**Comment by nicolaiarocci** [comment]
Questo progetto è per NetStandard 2.0 (a differenza di FattturaElettronica che è NS1.1). Hai bisogno di NET Framework 4.6.1 minimo per poterlo usare.
