### ISSUE TITLE
ReadXmlSigned e ReadXmlSignedBase64

### ISSUE THREAD

**Issue by AMD-Andrea** [FatturaElettronica/FatturaElettronica.Extensions#47]
In fase di lettura documento firmato p7m mi da questo errore 
"Rilevati dati non validi al livello radice. Riga 1, posizione 1.
Vi do qualche dato della firma file non so se può essere utile
[IT03336420967_2BIG6.xml.zip](https://github.com/FatturaElettronica/FatturaElettronica.Extensions/files/2893676/IT03336420967_2BIG6.xml.zip)

Ente certificatore ARUBA
Certificato X509
Algoritmo digest 2.16.840.1.101.3.4.2.1 (SHA256)

A qualcuno è già successo?
Allego file

**Comment by nicolaiarocci** [comment]
Ciao,

Ho provato e me lo legge senza problemi con `ReadXmlSigned`. Stai usando ultima versione del package?

**Comment by AMD-Andrea** [comment]
Ciao, si ultima versione, sto sviluppando con Visual Studio 2017 framework 4.6.1
Andrea Visonà – A.M. D. Software S.r.l.
Via Don Ettore Cazzaniga, 25 – 20845 Sovico (MB)
www.amdsoftware.it
RISERVATEZZA DELLE INFORMAZIONI
Questo messaggio e i documenti allegati, se ve ne sono, sono indirizzati esclusivamente ai destinatari in indirizzo e possono contenere informazioni riservate e protette da diritti professionali, la cui diffusione è tutelata dalla legge. Pertanto chiunque riceva questo messaggio e non appaia tra gli indirizzi dei destinatari o non sia autorizzato a riceverlo, è informato della riservatezza delle informazioni e del divieto di utilizzo di copia e diffusione. Se questo messaggio è stato ricevuto per errore, Vi chiediamo di informarci con un' e-mail o telefonando al n. +39 039 2324578, e di provvedere a distruggerlo immediatamente. La trasmissione in Internet di messaggi via e-mail, non garantisce la riservatezza dei messaggi inviati, e neppure la sicura ricezione. Se i destinatari in indirizzo non consentono l'uso di Internet per l'invio di tali messaggi, sono pregati di comunicarlo all'indirizzo sopra menzionato
Da:
Nicola Iarocci
A:
FatturaElettronica/FatturaElettronica.Extensions
Cc:
AMD-Andrea
Author
Data:
22 febbraio 2019 18.53.55 CET
Oggetto:
Re: [FatturaElettronica/FatturaElettronica.Extensions] ReadXmlSigned e ReadXmlSignedBase64 (#47)
Ciao,
Ho provato e me lo legge senza problemi con
ReadXmlSigned
. Stai usando ultima versione del package?
—
You are receiving this because you authored the thread.
Reply to this email directly,
view it on GitHub
, or
mute the thread
.

**Comment by AMD-Andrea** [comment]
Ciao, risolto il problema precedente era un mio errore di lettura file
Grazie
