### ISSUE TITLE
installazione non riuscita

### ISSUE THREAD

**Issue by sanzo88** [FatturaElettronica/FatturaElettronica.Extensions#48]
Non riesco ad installare il pacchetto con NuGet, sto utilizzando il framework 4.6.1.

Riporto il messaggio di errore:
Could not install package 'FatturaElettronica.Extensions 1.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework.

**Comment by nicolaiarocci** [comment]
A differenza di FatturaElettronica che è netstandard 1.1, Extensions è 2.0. Detto questo, sul 461 dovrebbe girare senza problemi. Hai poi risolto?
