### ISSUE TITLE
Esporta html

### ISSUE THREAD

**Issue by ZeusZoe** [FatturaElettronica/FatturaElettronica.Extensions#54]
Ciao,
innanzitutto volevo ringraziarti perchè è una utility veramente utile.

Ho visto che nella nuova release hai inserito una nuova funzionalità, quella di esportare un file html.
Sto rpovando ad usarla ma mi genera il seguente errore:
"System.PlatformNotSupportedException: Compilation of XSLT is not supported on this platform".
La mia è un'app UWP.

Saluti

**Comment by nicolaiarocci** [comment]
Ciao, direi che il messaggio è piuttosto auto-esplicativo. Personalmente non ho esperienza su UWP quindi non saprei suggerirti nemmeno un work-around.
