### ISSUE TITLE
Problemi installazione su framework 4.6.1

### ISSUE THREAD

**Issue by umbizeta** [FatturaElettronica/FatturaElettronica.Extensions#56]
Ciao, provando ad installare le Extensions, Nuget mi riporta il seguente errore ( ovviamente il framework di destinazione è il 4.6.1) :

"Non è stato possibile installare il pacchetto 'FatturaElettronica.Extensions 2.0.0'. Si sta tentando di eseguire l'installazione in un progetto destinato a '.NETFramework,Version=v4.6.1', ma il pacchetto non contiene riferimenti ad assembly o file di dati compatibili con il framework. Per altre informazioni, contattare l'autore del pacchetto.

Qualche idea?
grazie
U.

**Comment by nicolaiarocci** [comment]
Ciao, su VS2017 nuovo progetto NET461 Console, Extensions 2.0 si installa senza problemi (appena provato.)

**Comment by umbizeta** [comment]
Ciao Nicola, è un piacere.
Anche io sto provando un progetto nuovo  su Visual Studio 2015, purtroppo non carico le Extension.
Framework 4.6.1
Ho fatto anche tutti gli aggiornamenti ( uno per uno!) ma putroppo con VS2015 c'è questo problema
un saluto

**Comment by nicolaiarocci** [comment]
Ora non riesco a controllare (sono all'estero) ma mi sembra di ricordare che con VS2015 ci siano problemi a usare il 461 con NetStandard 2.0. Non e' un problema della libreria in se', comunque. Non puoi fare aggiornamento al 2017? Tra due settimane esce il 2019 :-)

**Comment by umbizeta** [comment]
magari...dipendesse da me....
se cambiassi il net framework? 
quale suggerisci?
grazie mille
