### ISSUE TITLE
Calcolare Hash Fattura

### ISSUE THREAD

**Issue by forons** [FatturaElettronica/FatturaElettronica.Extensions#62]
Una cosa interessante e utile sarebbe una funzione riguardante il calcolo dello SHA-256 per le fatture.
La cosa non sembra per nulla complicata, ma con il codice sotto riportato su un centinaio di fatture solo il 60 % circa produce l'hash code ricevuto nei metadati di risposta da parte dello SdI.
Pensavo fosse un problema di encoding o di line terminators, ma non ho trovato soluzioni.

Avevate intenzione di un sviluppare un metodo simile?

Grazie mille

```
        public static string HashSHA256(this string @this)
        {
            using (var hash = SHA256.Create())
            {
                var bytes = hash.ComputeHash(Encoding.UTF8.GetBytes(@this));
                var result = bytes.Aggregate(string.Empty, (current, b) => current + b.ToString("x2"));
                return result;
            }
        }
```

**Comment by nicogis** [comment]
Se vuoi provare con la libreria che sviluppato: https://nicogis.github.io/FatturazioneElettronica-Extensions/ . Il calcolo lo effettuo con chilkat (guarda nell'esempio)
